const FETCH_SUCCESS = "FETCH_SUCCESS"
const FETCH_FAILURE = "FETCH_FAILURE"
const PAGINATE_UPDATE = "PAGINATE_UPDATE"
const HANDLE_NEXT_PAGINATION = "HANDLE_NEXT_PAGINATION"
const HANDLE_PREV_PAGINATION = "HANDLE_NEXT_PAGINATION"
const SET_PAGE_CURRENT = "SET_PAGE_CURRENT"

export { FETCH_SUCCESS, FETCH_FAILURE, PAGINATE_UPDATE, HANDLE_NEXT_PAGINATION, HANDLE_PREV_PAGINATION, SET_PAGE_CURRENT };